---
records:
  - zone: 'local.langhome.net'
    ip: '192.168.1.51'
    name: '@'
  - zone: 'local.langhome.net'
    ip: '192.168.1.52'
    name: '@'
  - zone: 'local.langhome.net'
    ip: '192.168.1.181'
    name: 'gitea'
  - zone: 'local.langhome.net'
    ip: '192.168.1.185'
    name: 'gotify'
  - zone: 'local.langhome.net'
    ip: '192.168.1.185'
    name: 'guacamole'
  - zone: 'local.langhome.net'
    ip: '192.168.1.185'
    name: 'it-tools'
  - zone: 'local.langhome.net'
    ip: '192.168.1.185'
    name: 'jellyfin'
  - zone: 'local.langhome.net'
    ip: '192.168.1.185'
    name: 'jellyseer'
  - zone: 'local.langhome.net'
    ip: '192.168.1.185'
    name: 'n8n'
  - zone: 'local.langhome.net'
    ip: '192.168.1.1'
    name: 'opnsense'
  - zone: 'local.langhome.net'
    ip: '192.168.1.53'
    name: 'pihole'
  - zone: 'local.langhome.net'
    ip: '192.168.1.185'
    name: 'pinchflat'
  - zone: 'local.langhome.net'
    ip: '192.168.1.185'
    name: 'portainer'
  - zone: 'local.langhome.net'
    ip: '192.168.1.197'
    name: 'pve01'
  - zone: 'local.langhome.net'
    ip: '192.168.1.189'
    name: 'pve02'
  - zone: 'local.langhome.net'
    ip: '192.168.1.186'
    name: 'pve03'
  - zone: 'local.langhome.net'
    ip: '192.168.1.51'
    name: 'technitium01'
  - zone: 'local.langhome.net'
    ip: '192.168.1.52'
    name: 'technitium02'
  - zone: 'local.langhome.net'
    ip: '192.168.1.185'
    name: 'traefik'
  - zone: 'local.langhome.net'
    ip: '192.168.1.184'
    name: 'beszel'
  - zone: 'local.langhome.net'
    ip: '192.168.1.201'
    name: 'dockerhost01'
  - zone: 'local.langhome.net'
    ip: '192.168.1.198'
    name: 'dockerhost02'
  - zone: 'local.langhome.net'
    ip: '192.168.1.184'
    name: 'dockerhost03'
    