---
base_address: 'https://technitium02.local.langhome.net:53443'
dns_configurations:
        token: !vault |
                $ANSIBLE_VAULT;1.1;AES256
                37336535636635343463373731323564303434643561333432373332336134353030643834373930
                6564303331666336396563386565356333646364313965370a643663383162623162356634633665
                36613565616436636635303931643861363363366265663138316166366361323034623036633765
                3737373939306563660a383538616634336362336436386461326334343733323038663539643837
                37383737353631613464613935633863623531663434386363326261666462646638393637356265
                61363235636537356262353935656230656231366236633965656161366435656232346435663031
                31326430616235383065363035393236343830313064393364353433616136626332353164346436
                38613766393933306663