---
base_address: 'https://192.168.1.51:53443'
dns_configurations:
        token: !vault |
                $ANSIBLE_VAULT;1.1;AES256
                36383833636663316263353733636132353338383930616435626435333762363066666434616166
                3031633361373032353664666632333939356463653339360a653135616531333061613233363166
                61353064346264313236306365396663323434626565366261313766356439393833353766323462
                3162613636353161380a663935366434613738303234646463633237616163653361346461393936
                66656432303136356233343134633833616535313661303135363434643465316235393733643365
                32373061316564636663393135363834643665653738343436346636346137353663663062666234
                31386235663761366630396566396532666464393433616362306536333534336232653732636635
                63626336613866616131