name: Sync DNS Records

on:
  push:
    branches:
      - main
    paths:
      - 'roles/technitium/vars/records.yml'

jobs:
  sync-dns:
    runs-on: [self-hosted]
    env:
      VAULT_PASS: ${{ secrets.VAULT_PASS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false
          fetch-depth: 1

      - name: Install Ansible
        run: |
          pip install --no-cache-dir ansible

      - name: Debug working directory
        run: pwd && ls -la

      - name: Write vault password to file
        run: echo "$VAULT_PASS" > vault_pass.txt

      - name: Run Ansible Playbook
        run: |
          export ANSIBLE_CONFIG=$(pwd)/ansible.cfg
          ansible-playbook -v --vault-password-file vault_pass.txt \
            playbooks/sync_selected_dns.yml -e "target_servers=technitium01,technitium02"
